### ISSUE TITLE
Show entity annotations in error report from `rasa_nlu.test`

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa_nlu#1770] opened 2019-03-11 15:30 UTC
Results in `errors.json` current look like this:
```
    {
        "text": "hello i have a question. is there a mexican restaurant in paris?"
        ...
    }
```
Would be nice to have the entities annotated since that's how they look in the training data, i.e.
```
    {
        "text": "hello i have a question. is there a [mexican](cuisine) restaurant in [paris](location)?"
        ...
    }
```

**Comment by akelad** [comment] 2019-03-12 08:45
hmm this raises the question of whether those are entity errors or intent errors though

**Comment by erohmensing** [comment] 2019-03-15 17:49
Currently only intent errors are logged to `errors_filename`(default `errors.json`). Each entity extractor gets its own `<extractor>_report.json` with evaluation metrics from sklearn, but i don't think we currently have a list of error sentences for entity extraction 😬

**Comment by erohmensing** [comment] 2019-03-18 17:08
@akelad I actually just had someone asking if it's possible to see the list of entity extraction errors, think that's something worth adding to my nlu test refactor? (i realize this is relatively unrelated to toms actual issue here)

**Comment by akelad** [comment] 2019-03-19 11:17
@erohmensing let's focus on the refactor for now, if there's time and it's super easy to do, then sure :)

**Comment by erohmensing** [comment] 2019-03-19 13:48
sounds good. i'll create a separate feature request for it

**Comment by akelad** [comment] 2019-03-27 17:22
closing, duplicate of #1472

**Closed by akelad** 2019-03-27 17:22 UTC
Labels: enhancement
