### ISSUE TITLE
Exception: Failed to execute custom action

### ISSUE THREAD

**Issue by tiwo19** [RasaHQ/rasa_nlu#3161] opened 2019-03-27 12:18 UTC
Rasa Core version:0.13.2

Python version: python3.6.8

Operating system (windows, osx, ...):win10

Issue:
2019-03-26 21:21:44 DEBUG urllib3.connectionpool - Starting new HTTP connection (1): localhost
2019-03-26 21:21:46 DEBUG rasa_core.tracker_store - Recreating tracker for id 'default'
2019-03-26 21:21:46 DEBUG rasa_core.actions.action - Calling action endpoint to run action 'actions.GetJabuinfo'.
2019-03-26 21:21:46 DEBUG urllib3.connectionpool - Starting new HTTP connection (1): localhost
2019-03-26 21:21:47 DEBUG urllib3.connectionpool - http://localhost:5055 "POST /webhook HTTP/1.1" 500 290
2019-03-26 21:21:47 ERROR rasa_core.actions.action - Failed to run custom action 'actions.GetJabuinfo'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
2019-03-26 21:21:47 ERROR rasa_core.processor - Encountered an exception while running action 'actions.GetJabuinfo'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-03-26 21:21:47 ERROR rasa_core.processor - Failed to execute custom action.
Traceback (most recent call last):
File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core\actions\action.py", line 313, in run
response.raise_for_status()
File "C:\Users\damipe\Desktop\env\lib\site-packages\requests\models.py", line 935, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core\processor.py", line 319, in _run_action
events = action.run(dispatcher, tracker, self.domain)
File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core\actions\action.py", line 334, in run
raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.

Content of configuration file (config.yml):

language: "en"

pipeline: "tensorflow_embedding"
Content of domain file (domain.yml) (if used & relevant):

slots:
  group:
    type: text

intents:
 - greeting
 - get_jabu
 

entities:
 - product
 - jabuinfo

templates:
  utter_greet:
    - "Hello! What can I do for you?"

actions:
 - utter_greet
 - actions.GetJabuinfo

**Comment by erohmensing** [comment] 2019-03-28 08:16
duplicate of #3157

**Closed by erohmensing** 2019-03-28 08:16 UTC
