### ISSUE TITLE
Spacy version upgrade in rasa_nlu  

### ISSUE THREAD

**Issue by pvagare** [RasaHQ/rasa_nlu#785] opened 2018-01-18 06:49 UTC
Hi Team,
I am using latest rasa_nlu version. I have one question around Spacy. current we are using the spacy nlp 1.8.0 library but spacy has upgraded its version and come up with new features.
Is there plan to upgrade Spacy version to 2.0.0 in latest rasa_nlu ? 

Please let me know.
Thanks !

**Comment by wrathagom** [comment] 2018-01-18 13:11
Duplicate of #456 please see conversation there.

**Closed by wrathagom** 2018-01-18 13:11 UTC
