### ISSUE TITLE
Unable to train SpaCy pipeline in Ubuntu 16.04 with rasa_nlu(0.9.0)

### ISSUE THREAD

**Issue by ankitksharma** [RasaHQ/rasa_nlu#495] opened 2017-07-21 12:18 UTC
**rasa NLU version** (e.g. `0.9.0`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (ubuntu 16.04):

**Issue**:

I have setup the pipeline and was able to train models properly in my Mac machine. I have created a Conda virtual environment and exported the requirement file from both conda and pip and installed all dependencies in Ubuntu. I'm able to train MITIE pipeline. But when I try to train with the following pipeline, I get "tokens" not found error in ner_crf

**Pipeline**:
["nlp_spacy", "ner_crf", "ner_synonyms", "intent_featurizer_spacy", "intent_classifier_sklearn"]

**Exception**:
_Failed to validate at component 'ner_crf'. Missing property: 'tokens'_

**Installation file**
```
# Create a new virtual environment
conda create -n rasa numpy scipy scikit-learn matplotlib jupyter python=2.7
source activate rasa
# Install Rasa dependencies
pip install -r rasa_nlu/dev-requirements.txt
# Install necessary python package
pip install rasa_nlu==0.9.0
conda install spacy
python -m spacy download en
```

Everything works perfectly fine in MacOS. Does anyone has any idea?

**P.S. Possibly a duplicate of #362 but suggested help didn't work.**

**Comment by PHLF** [comment] 2017-07-21 12:36
Hi! A possible duplicate of #362 but a certain duplicate of #492 😉

**Comment by tmbo** [comment] 2017-07-21 12:38
Either retrain or add `tokenizer_spacy` after `"nlp_spacy"`.

**Closed by tmbo** 2017-07-21 12:38 UTC
