### ISSUE TITLE
training gets killed sometimes

### ISSUE THREAD

**Issue by AP8050** [RasaHQ/rasa_nlu#483] opened 2017-07-17 10:11 UTC
**rasa NLU version** (e.g. `0.10`):

**Used backend / pipeline** (`mitie`):

**Operating system** (ubuntu):

**Issue**:
While training it gets stopped(killed). If I try to train the same data again and again(2 to 3 times),its getting trained. I just  want to know why the training was killed at sometimes.
no of categories : 9
no of samples : 16 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment] 2017-07-17 19:24
Is there an error message you get or some other information you can share with us that makes this reproducible?

**Comment by AP8050** [comment] 2017-07-18 05:26
When I do training, it was killed without throwing any error and when I do training after sometime it gets trained. In both cases training data remains the same.**Refer both screenshots attached.**

![10-killed](https://user-images.githubusercontent.com/28773997/28301719-4e5e89f6-6ba6-11e7-9032-7924daa0a975.png)


![10-trained](https://user-images.githubusercontent.com/28773997/28301853-605a7b46-6ba7-11e7-83d4-dcc48fd6c368.png)

**Comment by amn41** [comment] 2017-07-18 07:30
this looks like an out of memory error. How much ram do you have?

**Comment by AP8050** [comment] 2017-07-18 07:45
thanks for your reply @amn41.  I have 4GB ram. In general how much RAM is required?

**Comment by amn41** [comment] 2017-07-18 11:27
that should be OK, since you're training with a pretty small data set. Try using `top` to track the memory while the training runs. But your OS is killing the process, which usually means it's consuming too many resources

**Comment by AP8050** [comment] 2017-07-18 11:44
If I want to train more than 200 samples. How much RAM is required?

**Comment by wrathagom** [comment] 2017-07-18 21:15
From my understanding the MITIE or Spacy model plus your training data set all have to fit into memory. Plus some overhead. Plus any previously loaded models.

Looks like you may have MySQL running at the same time, which can use a chunk of RAM.

**Comment by AP8050** [comment] 2017-07-24 05:57
Thanks @wrathagom . I will increase the RAM and check it.

**Comment by iKaos** [comment] 2017-07-24 18:19
You could increase your swap size.

**Comment by wrathagom** [comment] 2017-07-27 12:45
@AP8050 I'm closing, let us know if you weren't able to resolve this issue.

**Comment by AP8050** [comment] 2017-07-28 11:41
I increased the Ram from 4GB to 8GB. I have 16  intents with 73 samples and I tracked the memory while the training runs. It didn't consume any other resources. Only Trainingdata.json is created after that the training process gets killed.

**Comment by wrathagom** [comment] 2017-07-28 12:35
Okay, to help we're going to need more information, and not in screenshots. Either post in gists or In your response the actual text.

Can you provide:
- Operating System
- Rasa version
- complete config file
- Complete training data (in a gist or privately e-mailed if you don't want to share publicly)

**Comment by AP8050** [comment] 2017-08-16 11:50
I've mailed you the information you asked for on Aug 01, 2017. Please check with it. @wrathagom

**Comment by wrathagom** [comment] 2017-08-16 12:37
I see it now, will try to get some time to play with this today.

**Comment by AP8050** [comment] 2017-09-04 12:13
@wrathagom what happened?did you checked with that?

**Comment by chenxian01** [comment] 2017-09-18 10:15
I run into the same problem. Did this fixed?

**Comment by tmbo** [comment] 2017-09-18 10:17
I couldn't reproduce this yet, which makes it hard to fix. @chenxian01 are you running the latest version from github?

**Comment by chenxian01** [comment] 2017-09-18 10:28
Yes, I use the latest version. And I tried on my Ubuntu16.04 & Ubuntu17.04. I have 71 examples. When I trained the model, after a long long time, then they will show killed.

**Comment by tmbo** [comment] 2017-09-18 10:30
@chenxian01 how much memory are you using and which pipeline is specified in your configuration?

**Comment by chenxian01** [comment] 2017-09-18 10:33
I use 2G memory and pipline is mitie.

**Comment by tmbo** [comment] 2017-09-18 10:34
mitie is most likely running out of memory there. either use spacy or use a machine with more memory.

**Comment by chenxian01** [comment] 2017-09-18 10:36
I don't have too much memory in my machine. How much memory is enough? And the entity recognoziton for spacy is not better than mitie, sometimes it will give wrong prediction.

**Comment by wrathagom** [comment] 2017-09-19 02:58
entity recognition for spacy can perform just as well as MITIE, it just needs to be trained properly, which likely just means more training examples.

Memory for MITIE is hard to calculate, but the .dat file it uses is > 1GB. Plus you'll need room to train you're model. I'd say you need at least 2-4 GB of RAM free before starting Rasa. That number increases as your number of intents increases.

**Comment by wrathagom** [comment] 2017-09-19 03:14
@AP8050 sorry didn't realize I never responded. Was your training data modified before you sent it to me? There was a missing `,` on line 262.

I am training right now to see if it succeeds for me.

**Closed** 2017-09-25 12:28 UTC
Labels: irreproducible, question

**Comment by avi0gaur** [comment] 2018-02-17 11:33
Hi I see this thread has been closed, I am facing same issue with Spacy_Sklearn, I am running my script on 8gb ram. While calling parse method rasa_nlu is making a sudden spike in CPU, which lead to killing the script specially if you are running it on cloud instance.

**Comment by sdu-2044** [comment] 2019-06-28 01:36
I am facing same issue with rasa 1.1.4.my config is
 `language: "zh"

pipeline:
- name: "tokenizer_jieba"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_duckling_http"
  language: "zh$core"
  dimensions: ["time","number","duration","phone-number"]
- name: "intent_featurizer_count_vectors"
  OOV_token: oov
  token_pattern: '(?u)\b\w+\b'
- name: "intent_classifier_tensorflow_embedding"`
My training data  has a size of 118m . 2 intents  2789856 entity examples (1 distinct entities)
And an run the project on centos with 8 cpu cores and  528020320 KB   memery.
hopes for reply ,thanks

**Comment by mohsen202** [comment] 2023-10-06 12:53
i have the same problem  . please help me
