### ISSUE TITLE
"Not all required packages are installed. Please install sklearn" when setting up a new project

### ISSUE THREAD

**Issue by m90** [RasaHQ/rasa_nlu#1315] opened 2018-08-15 08:33 UTC
**Rasa NLU version**: 0.13.1

**Operating system** (windows, osx, ...): Ubuntu 16

**Issue**:

I'm trying to set up a new nlu-only application using the tensorflow pipeline. To do so, I created a new virtualenv and installed `rasa_nlu[tensorflow]`:

```
python3.6 -m venv venv
source venv/bin/activate
pip install rasa_nlu[tensorflow]
```

`pip freeze` prints the following now:

```
(venv) ➜  new-nlu git:(master) ✗ pip freeze                        
absl-py==0.4.0
astor==0.7.1
attrs==18.1.0
Automat==0.7.0
boto3==1.7.77
botocore==1.10.77
certifi==2018.8.13
chardet==3.0.4
cloudpickle==0.5.3
coloredlogs==10.0
constantly==15.1.0
cycler==0.10.0
docutils==0.14
future==0.16.0
gast==0.2.0
gevent==1.3.5
greenlet==0.4.14
grpcio==1.14.1
humanfriendly==4.16.1
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
jmespath==0.9.3
jsonschema==2.6.0
kiwisolver==1.0.1
klein==17.10.0
Markdown==2.6.11
matplotlib==2.2.3
numpy==1.15.0
packaging==17.1
pathlib==1.0.1
pkg-resources==0.0.0
protobuf==3.6.1
PyHamcrest==1.9.0
pyparsing==2.2.0
python-crfsuite==0.9.6
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.13
rasa-nlu==0.13.1
requests==2.19.1
s3transfer==0.1.13
scikit-learn==0.19.2
simplejson==3.16.0
six==1.11.0
sklearn-crfsuite==0.3.6
tabulate==0.8.2
tensorboard==1.10.0
tensorflow==1.10.0
termcolor==1.1.0
tqdm==4.24.0
Twisted==18.7.0
typing==3.6.4
urllib3==1.23
Werkzeug==0.14.1
zope.interface==4.5.0
```

I copied the `nlu.md` file from [here](http://rasa.com/docs/nlu/quickstart/) and my `nlu_config.yml` looks like:

```yml
language: en
pipeline: tensorflow_embedding
```

When I now try to run the training as described in the tutorial, I will get an error:

```
(venv) ➜  new-nlu git:(master) ✗ python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models
 --fixed_model_name nlu --project current --verbose
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frederik/projects/new-nlu/venv/lib/python3.6/site-packages/rasa_nlu/train.py", line 1
74, in <module>
    num_threads=cmdline_args.num_threads)
  File "/home/frederik/projects/new-nlu/venv/lib/python3.6/site-packages/rasa_nlu/train.py", line 1
43, in do_train
    trainer = Trainer(cfg, component_builder)
  File "/home/frederik/projects/new-nlu/venv/lib/python3.6/site-packages/rasa_nlu/model.py", line 1
52, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/frederik/projects/new-nlu/venv/lib/python3.6/site-packages/rasa_nlu/components.py", l
ine 63, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the mis
sing dependencies. Please install sklearn
```

I noticed `sklearn` is not in what `pip freeze` prints, so I tried to install it:

```
(venv) ➜  new-nlu git:(master) ✗ pip install sklearn
Collecting sklearn
Requirement already satisfied: scikit-learn in ./venv/lib/python3.6/site-packages (from sklearn) (0.1
9.2)
Installing collected packages: sklearn
Successfully installed sklearn-0.0
```

Now `pip freeze` will include `sklearn==0.0`, yet when I try to run the training, I will get the same error.

I think this might be related to #1309 but I have hard time understanding what the actual fix for the issue was in there.

**Comment by m90** [comment] 2018-08-15 08:56
Weirdly this is being fixed by running

```
pip install scipy
```

which I found by running

```
(venv) ➜  new-nlu git:(master) ✗ python -c "import sklearn"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/frederik/projects/new-nlu/venv/lib/python3.6/site-packages/sklearn/__init__.py", line
 134, in <module>
    from .base import clone
  File "/home/frederik/projects/new-nlu/venv/lib/python3.6/site-packages/sklearn/base.py", line 11,
 in <module>
    from scipy import sparse
ModuleNotFoundError: No module named 'scipy'
```

Don't know what the cause of this though and if it can be fixed.

**Comment by Ghostvv** [comment] 2018-08-15 09:37
This is a bug in https://github.com/RasaHQ/rasa_nlu/blob/d3fe1dbd5f960cb2239e5358832c295aee27ed95/rasa_nlu/components.py#L55
The problem is that it fails to import `sklearn` due to lack of `scipy` and `rasa_nlu` prints an error that there is no sklearn

**Comment by m90** [comment] 2018-08-15 09:50
Does this mean `scipy` needs to be added to the `install_packages` in `setup.py`? Is it required for all pipelines? At the moment it's only included in the `[spacy]` extras.

**Comment by Ghostvv** [comment] 2018-08-15 09:52
Yes, I think `sklearn` always requires `scipy`: http://scikit-learn.org/stable/install.html

**Comment by Ghostvv** [comment] 2018-08-16 08:01
PR is merged

**Closed by Ghostvv** 2018-08-16 08:01 UTC
Labels: bug
