### ISSUE TITLE
Composite entities support

### ISSUE THREAD

**Issue by natreen** [RasaHQ/rasa_nlu#316] opened 2017-04-28 09:48 UTC
It would be very helpful if composite entities would be supported, these are entities that have a hierarchical structure. For example: "I need a red dress with blue dots" or "The shirt should be not yellow" or "I need a red shirt and blue sneakers". 

In wit.ai they have those entities and they're very helpful: https://wit.ai/blog/2015/05/05/composite-entity

**Comment by twerkmeister** [comment] 2017-05-02 00:55
@natreen from my understanding this is a duplicate of #267 . Do you think so too?

**Comment by chatShopper** [comment] 2017-05-02 09:29
I'm not so sure if we mean the same. For me #267 sounds more like word-compounds (two entities for one word) and I rather mean nested entities.

**Comment by kirsanau** [comment] 2017-06-21 06:04
this feature is super useful, was trying to import api.ai agent with composite entities and realized that this is not yet supported ((
more on the use case behind it you can find here
https://docs.api.ai/docs/concept-entities#section-developer-composite-entities

**Comment by kirsanau** [comment] 2017-06-21 10:02
actually now, when i faced that composite entities is not available in rasa, i am kind of stuck how to handle following situation.
imagine i need to compare sales of 2 configuration of cars
so my question would be:
"please give me sales of red sport convertible cars compared to sport hatchback cars in june 2017"

with composite entity i would identify 2 cars entites with following attributes (works in api.ai)
car1{ color:red, trim:sport, chassis:convertible}
car2{trim:sport, chassis:hatchback}

in rasa i need to make it 3 different entities and i will get a response
color:[red]
trim:[sport,sport]
chassis[convertible, hatchback]
from this i can figure out user is talking about 2 cars ( length of array > 1), but to which car shall assign red, to the first or to the second is not clear.

may be you can suggest how to handle this.

**Comment by amn41** [comment] 2017-06-21 10:17
We don't have a general purpose feature for this yet, but you can write something for your particular case using spaCy's parse tree. Here's how the parse looks for [this sentence](https://demos.explosion.ai/displacy/?text=please%20give%20me%20sales%20of%20red%20sport%20convertible%20cars%20compared%20to%20sport%20hatchback%20cars%20in%20june%202017&model=en&cpu=1&cph=1). 

So you can identify relationships using each token's `ancestors` attribute, or example. See [here](https://spacy.io/docs/usage/dependency-parse)

**Comment by PHLF** [comment] 2017-06-21 10:34
AFAIK, that would need either a new component for entity classification using a structured classifier like a structured SVM instead or adding some changes to the existing CRF component as CRF is by nature a strructured classfiffier.

**Comment by kirsanau** [comment] 2017-06-21 10:44
amn41, thanks for suggestion
for now looks complex for me to write it, i do no know python.
what i am thinking of is to create entity car with all possible combinations of attributes (likely i have 3 only) like
red
red sport
sport red
red sport hatchback
red hatchback sport
hatchback red sport
etc...

**Comment by bigman73** [comment] 2017-06-21 10:54
@amn41 This is really useful info. 
How can Rasa provide this data? Does it expose the spacy information?
Or does it mean a new spacy instance is needed, outside of the scope of Rasa?

**Comment by amn41** [comment] 2017-06-21 12:12
you could either write a new component, which accesses the spacy language object (`spacy_nlp`), see an example here: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/featurizers/spacy_featurizer.py#L23 

otherwise yes you could load a separate spacy instance somewhere in your application.

**Comment by bigman73** [comment] 2017-06-21 12:18
Great. 
That's my next question - maybe Rasa can expose the 'featurizer' as a REST API?

**Comment by datascienceteam01** [comment] 2018-03-08 22:21
What is the status on this one? Is there any current form of building nested entities? I need to build something like this -> 
_"List of Walmart purchases:
   Boots, 28 March
   Tent, 30 March"_
as
walmart_purchase{
item:boots
date:03-28-2018 }
walmart_purchase(
item:tent
date:03-30-2018
}

**Comment by samhavens** [comment] 2018-10-10 19:42
My team got this working, but it's messy. We'd like to talk to someone (@amn41 ?) about how to make the integration cleaner.

**Comment by akelad** [comment] 2018-10-11 08:27
@samhavens is this something you'd be willing to share with the community?

**Comment by samhavens** [comment] 2019-01-07 15:36
Our PR handling this within Rasa NLU wasn't getting merged, so we figured out how to do this as a custom component. We've open sourced it in [Innatis](https://github.com/Revmaker/innatis). Let us know if you have trouble getting it working, as so far we are our only consumers, so docs are probably lacking.

**Comment by akelad** [comment] 2019-01-08 08:17
@samhavens sorry about that, we're looking into the PR in detail this week :)

**Comment by akelad** [comment] 2019-01-09 14:33
if we find it's essential though we'd still like to add it to the code base :)

**Comment by samhavens** [comment] 2019-01-09 17:44
Cool! Just keep us posted. It should make migration from DF->Rasa easier

**Comment by BeWe11** [comment] 2019-01-25 09:54
Hey, we have released our own component that handles composite entities at https://github.com/BeWe11/rasa_composite_entities. Maybe this can be of use to some people here.

**Comment by akelad** [comment] 2019-01-25 16:48
@BeWe11 thanks for sharing as well :) 
I think we can close this issue now, as the feature exists in multiple libraries

**Closed by akelad** 2019-01-25 16:48 UTC
Labels: enhancement
