### ISSUE TITLE
Training crashes on large set of expressions/intent

### ISSUE THREAD

**Issue by sourjatilak** [RasaHQ/rasa_nlu#239] opened 2017-03-27 10:50 UTC
rasa NLU version: 0.7.3 (and below)
Used backend (`mitie_sklearn`) & plattform (ubuntu/osx)
Issue: 
The number of expressions that I have is around 5900 and the number of intent mapping is around 800.
When I am training the model, after half an hour , the python command exits wihout any error message. After that I am finding the model that got created has very low accuracy. I believe the program is crashing for some reason.

Command used: python -m rasa_nlu.train -c config.json
Content of config.json:
{
  "backend": "mitie_sklearn",
  "path" : "./maindata/trained_models",
  "mitie_file": "./total_word_feature_extractor.dat",
  "data" : "./Training_set_27-02-2017_cleaned.json",
  "fine_tune_spacy_ner" : "true",
  "server_model_dirs" : "model_20170327-090308",
  "num_threads": 1024
}

My Hardware conf: Amazon r4.xlarge (4 core, 30.5 GB Ram, 16 GB SSD Hardrive)

The last output of the training command is:
/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
root@ip-172-31-11-64:~# 

Can you look into it please.

**Comment by sourjatilak** [comment] 2017-03-27 10:54
Hi

I tried with backend: mitie. I am experiencing the same thing:

The output:

Train classifier
extracting text features
now do training
num training samples: 5903
python: src/mitie.cpp:87: const T& {anonymous}::checked_cast(const void*) [with T = mitie::text_categorizer]: Assertion `ptr' failed.
Aborted (core dumped)

**Comment by tmbo** [comment] 2017-03-27 12:51
@sourjatilak I haven't experienced this so it would be helpful if I could access your data. If you don't mind, feel free to send it to tom@golastmile.com

**Comment by tmbo** [comment] 2017-03-27 12:53
Another thing you can try as well is to update to the latest master version by pulling and installing that copy instead of using the pypi published version. Make sure you use the correct documentation though (https://rasa-nlu.readthedocs.io/en/latest/)

**Comment by sourjatilak** [comment] 2017-03-29 13:50
I cloned from the latest git and was trying to train my model.
I am getting an error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/rasa_nlu-master/rasa_nlu/train.py", line 68, in <module>
    do_train(config)
  File "/root/rasa_nlu-master/rasa_nlu/train.py", line 56, in do_train
    training_data = load_data(config['data'], config['language'], luis_data_tokenizer=config['luis_data_tokenizer'])
  File "rasa_nlu/converters.py", line 187, in load_data
    fformat = guess_format(files)
  File "rasa_nlu/converters.py", line 157, in guess_format
    file_data = json.loads(f.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 87 - line 2 column 1 (char 86 - 627738)

Can you help me out please.

**Comment by amn41** [comment] 2017-03-29 14:27
This looks like an issue with your training data json file. Can you check for hidden characters? Does it work to load it with the [trainer](https://golastmile.github.io/rasa-nlu-trainer/) ?

**Comment by sourjatilak** [comment] 2017-03-29 14:51
Thanks, I got the issue solved using the trainer.
Now I am getting some other error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/rasa_nlu-master/rasa_nlu/train.py", line 68, in <module>
    do_train(config)
  File "/root/rasa_nlu-master/rasa_nlu/train.py", line 58, in do_train
    trainer.train(training_data)
  File "rasa_nlu/model.py", line 168, in train
    updates = component.train(*args)
  File "rasa_nlu/classifiers/sklearn_intent_classifier.py", line 69, in train
    self.clf.fit(X, y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_search.py", line 945, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_search.py", line 539, in _fit
    cv = check_cv(self.cv, y, classifier=is_classifier(estimator))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 1585, in check_cv
    return StratifiedKFold(cv)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 560, in __init__
    super(StratifiedKFold, self).__init__(n_splits, shuffle, random_state)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 280, in __init__
    " got n_splits={0}.".format(n_splits))
ValueError: k-fold cross-validation requires at least one train/test split by setting n_splits=2 or more, got n_splits=1.

**Comment by sourjatilak** [comment] 2017-03-29 15:00
I am using Mitie pipeline/backend.
(Version of Rasa: 0.8.0a3)

I am still getting the same error: 

Train classifier
extracting text features
now do training
num training samples: 6317
python: src/mitie.cpp:87: const T& {anonymous}::checked_cast(const void*) [with T = mitie::text_categorizer]: Assertion `ptr' failed.
^[[C^[[AAborted (core dumped)

**Comment by amn41** [comment] 2017-03-30 05:28
my best guess is that you're running into trouble because of the large number of threads. What kind of hardware are you running on? Figuring out the optimal number of threads is something you just have to try to get right, but I would suggest using the same order of magnitude as the number of cores on your machine. So if you have an 8 core CPU 1000 threads is far too many, because 99.9% of your threads will probably be idle at any given time. Try with somewhere between 1 and 16 threads.

**Comment by sourjatilak** [comment] 2017-03-30 08:20
Hi @amn41, 
I am using version of Rasa: 0.8.0a3
Config File:
{
  "pipeline": "mitie_sklearn",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./123.json"
}

I am still getting:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/rasa_nlu/rasa_nlu/train.py", line 68, in <module>
    do_train(config)
  File "/root/rasa_nlu/rasa_nlu/train.py", line 58, in do_train
    trainer.train(training_data)
  File "rasa_nlu/model.py", line 168, in train
    updates = component.train(*args)
  File "rasa_nlu/classifiers/sklearn_intent_classifier.py", line 69, in train
    self.clf.fit(X, y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_search.py", line 945, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_search.py", line 539, in _fit
    cv = check_cv(self.cv, y, classifier=is_classifier(estimator))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 1585, in check_cv
    return StratifiedKFold(cv)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 560, in __init__
    super(StratifiedKFold, self).__init__(n_splits, shuffle, random_state)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 280, in __init__
    " got n_splits={0}.".format(n_splits))
ValueError: k-fold cross-validation requires at least one train/test split by setting n_splits=2 or more, got n_splits=1.

**Comment by sourjatilak** [comment] 2017-03-30 08:25
@amn41 

Same is happening with Mitie

Config file:
{
"pipeline": "mitie",
"mitie_file": "./data/total_word_feature_extractor.dat",
"path" : "./models",
"data" : "./123.json"
}

Train classifier
extracting text features
now do training
num training samples: 6317
python: src/mitie.cpp:87: const T& {anonymous}::checked_cast(const void*) [with T = mitie::text_categorizer]: Assertion `ptr' failed.
Aborted (core dumped)

**Comment by tmbo** [comment] 2017-03-30 08:37
@sourjatilak I just pushed a small fix for the `mitie_sklearn ` backend that should resolve the cross-validation error.

**Comment by sourjatilak** [comment] 2017-03-30 12:03
Thanks @tmbo , It worked for mitie_sklearn.
The model got created but no testing happened on that. The number of expressions are 6K and number of intents is around 600.
(I mean if we have a json file with less number of intents, then some extra training happens/shows up and an overall accuracy would be shown). 
I also have checked the model using localhost:5000/parse, I am getting very low accuracy.
How do I boost/retest the input models as training is not doing any testing on the model.

**Comment by tmbo** [comment] 2017-04-03 14:26
The mitie model can not handle that many intents. Furthermore, even when using sklearn to train the intent classifier, you will need way more training data to train a proper model. I'd suggest thinking about reducing the number of intents dough.

**Comment by twerkmeister** [comment] 2017-05-02 00:53
Its seems we won't fix this? I suggest that we then close the issue

**Comment by tmbo** [comment] 2017-05-02 07:37
The issue isn't fixed and someone from the community might jump in to work on the mitie performance. I'd keep it open.

**Closed** 2017-05-23 15:11 UTC
