### ISSUE TITLE
 Failed to find component class for 'ner_spacy'

### ISSUE THREAD

**Issue by mega-coder** [RasaHQ/rasa_nlu#1058] opened 2018-04-30 22:51 UTC
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:

**Comment by mega-coder** [comment] 2018-04-30 22:52
hi , i'm trying to use ner_spacy  entities extraction like location and i got this error : 
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    trainer = Trainer(config.load("config_spacy.yml"))
  File "d:\Profiles\htazarki\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 146, in __init__
    components.validate_requirements(cfg.component_names)
  File "d:\Profiles\htazarki\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\components.py", line 54, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "d:\Profiles\htazarki\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\registry.py", line 116, in get_component_class
    "in a module.".format(component_name))
Exception: Failed to find component class for 'ner-spacy'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa_nlu.registry.py` or is a proper name of a class in a module.

**Comment by souvikg10** [comment] 2018-05-01 11:28
what is there in your pipeline? can you share your config, also the component should be called ner_spacy instead of ner-spacy as i see in your error

**Comment by mega-coder** [comment] 2018-05-01 12:15
hi yes  you are right , i chnaged  and i skiped that error  and now training goes fine but after starting the server and testing the result it seems that ner_spacy can't extract locations ,request always returns the entities array empty

**Comment by mega-coder** [comment] 2018-05-01 12:16
here is my config file :

language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_spacy"
- name: "ner_duckling"

**Comment by wrathagom** [comment] 2018-05-01 12:33
what text are you trying to parse? Does the spacy [demo](https://explosion.ai/demos/displacy-ent?text=I%20am%20from%20New%20York.%0A%0A&model=en_core_web_sm&ents=person%2Corg%2Cgpe%2Cloc%2Cproduct%2Cnorp%2Cdate%2Cper%2Cmisc) detect it?

**Comment by akelad** [comment] 2018-05-01 13:12
it's `ner_spacy` that's probably the issue 🙂

**Comment by wrathagom** [comment] 2018-05-04 00:40
@mega-coder were you able to try your text in the tool I linked above to test spacy outside of Rasa?

**Comment by wrathagom** [comment] 2018-05-07 16:34
Closing, but let us know if the issue is still a problem.

**Closed by wrathagom** 2018-05-07 16:34 UTC
Labels: question
