### ISSUE TITLE
attribute error while trying to train the dialogue model in rasa core. please help me soon thank

### ISSUE THREAD

**Issue by PKAAKAA1** [RasaHQ/rasa_nlu#949] opened 2018-03-27 15:00 UTC
i get this error when following the basic  rasa tutor help me

python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 300

/home/pi/berryconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/pi/berryconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pi/berryconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/rasa_core/train.py", line 122, in <module>
    additional_arguments)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/rasa_core/train.py", line 80, in train_dialogue_model
    agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy()])
  File "/home/pi/berryconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 42, in __init__
    self.domain = self._create_domain(domain)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 237, in _create_domain
    return TemplateDomain.load(domain)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 429, in load
    cls.validate_domain_yaml(filename)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 455, in validate_domain_yaml
    warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)
AttributeError: module 'ruamel.yaml.error' has no attribute 'UnsafeLoaderWarning'

**Comment by Harish0596** [comment] 2018-03-28 10:14
I think the problem is with your domain.yml 
check whether you have given any different name other than name that you have used for running the python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 300 command

**Comment by PKAAKAA1** [comment] 2018-03-28 18:11
this is my domain.yml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

**Comment by akelad** [comment] 2018-03-29 07:27
This is a duplicate of an issue in rasa core, so I'm going to close it. 
https://github.com/RasaHQ/rasa_core/issues/312

**Closed by akelad** 2018-03-29 07:27 UTC
