### ISSUE TITLE
MITIE and Chinese support

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_nlu#972] opened 2018-04-06 11:49 UTC
Attn: users who use Rasa NLU for Chinese. Could you please try your datasets (at least intent classification) with the new `tensorflow_embedding` pipeline? We would love to know how the performance is. 

We are thinking of dropping support for MITIE because training times are long, and in our regular performance benchmarks it doesn't show any advantages in terms of performance. 

However, to my knowledge most users who use Rasa to do Chinese NLU use MITIE, so I would love to understand how well alternatives do there.

**Comment by wrathagom** [comment] 2018-04-09 12:53
lol, always one for brevity. Though I am assuming the `No description provided` should read something like:

> Since removing MITIE we've discovered that MITIE was the closest/easiest path for our users to get Chinese NLU working. Now that we've removed it we may have to add it back for Chinese support or work to get spacy understanding Chinese.

Not trying to put words in your mouth or anything ;) Linking a couple issues here just for cross reference.

#975 
#705

**Comment by howl-anderson** [comment] 2018-04-10 12:11
As a spaCy contributor, I am currently working on adding Chinese language supporting to spaCy. Actually I already communicated with spaCy official developer about this. They are also working on this topic very hard. Additional features will be added to spaCy in a future version. I don't know the release date of spaCy with Chinese language supporting, but It will be released with a good performance in the near future. If there are more details, I will keep the RSAS community updated.

**Comment by tmbo** [comment] 2018-04-10 12:36
That sounds very promising!

**Comment by howl-anderson** [comment] 2018-04-11 03:44
Q: How long it will take before release of spaCy model with Chinese language supporting? (2018-04-11)
A: It’s hard to tell when the model will be released. Because the model must be tested that show a good/acceptable performance. spaCy also need make several changes to support Chinese, Japanese and Vietnamese. This will take time too.

**Comment by winner484** [comment] 2018-04-12 01:01
@howl-anderson  thank you!

**Comment by winner484** [comment] 2018-05-03 03:38
sapCy support Chinese language now. 
https://github.com/howl-anderson/Chinese_models_for_SpaCy
but entities can not be detected. need help!
step: 1 install zh_core_web_sm 
         2  python3 -m spacy link zh_core_web_sm zh
         3  train 
issue:  intent OK ,but don`t have any entities.
NEED HELP!

**Comment by wrathagom** [comment] 2018-05-03 04:16
@winner484 is it `ner_crf` not returning any entities or `ner_spacy`?

**Comment by winner484** [comment] 2018-05-03 06:14
@wrathagom never had an entity return. i have tried many text, but never had any entities return

**Comment by winner484** [comment] 2018-05-03 06:16
the metadata.json in Model is : 
{
    "training_data": "training_data.json",
    "pipeline": [
        {
            "case_sensitive": false,
            "model": "zh",
            "class": "rasa_nlu.utils.spacy_utils.SpacyNLP",
            "name": "nlp_spacy"
        },
        {
            "class": "rasa_nlu.tokenizers.spacy_tokenizer.SpacyTokenizer",
            "name": "tokenizer_spacy"
        },
        {
            "class": "rasa_nlu.featurizers.spacy_featurizer.SpacyFeaturizer",
            "name": "intent_featurizer_spacy"
        },
        {
            "regex_file": "regex_featurizer.json",
            "class": "rasa_nlu.featurizers.regex_featurizer.RegexFeaturizer",
            "name": "intent_entity_featurizer_regex"
        },
        {
            "class": "rasa_nlu.extractors.crf_entity_extractor.CRFEntityExtractor",
            "max_iterations": 50,
            "features": [
                [
                    "low",
                    "title",
                    "upper",
                    "pos",
                    "pos2"
                ],
                [
                    "bias",
                    "low",
                    "word3",
                    "word2",
                    "upper",
                    "title",
                    "digit",
                    "pos",
                    "pos2",
                    "pattern"
                ],
                [
                    "low",
                    "title",
                    "upper",
                    "pos",
                    "pos2"
                ]
            ],
            "L1_c": 1,
            "name": "ner_crf",
            "L2_c": 0.001,
            "BILOU_flag": true,
            "classifier_file": "crf_model.pkl"
        },
        {
            "class": "rasa_nlu.extractors.entity_synonyms.EntitySynonymMapper",
            "name": "ner_synonyms",
            "synonyms_file": "entity_synonyms.json"
        },
        {
            "class": "rasa_nlu.classifiers.sklearn_intent_classifier.SklearnIntentClassifier",
            "name": "intent_classifier_sklearn",
            "classifier_file": "intent_classifier_sklearn.pkl",
            "max_cross_validation_folds": 5,
            "C": [
                1,
                2,
                5,
                10,
                20,
                100
            ],
            "kernels": [
                "linear"
            ]
        }
    ],
    "trained_at": "20180503-103724",
    "language": "zh",
    "rasa_nlu_version": "0.12.3"
}

**Comment by winner484** [comment] 2018-05-03 09:25
终于搞定了，但是为什么无法显示汉字，显示的是"text": "\u6211\u60f3\u5403\u706b\u9505"

**Comment by wrathagom** [comment] 2018-05-03 12:40
@winner484 speaking without being able to read the language 😅 are you providing more entity examples than just that? entities can take a lot of data to train. Also if `火锅` is really the entity then it is mislabeled. I believe the training data should have a range from 3 to 5 instead of 2 to 5.

```
{
  "text": "我想吃火锅啊",
    "intent": "restaurant_search",
    "entities": [
      {
        "start": 3,
        "end": 5,
        "value": "火锅",
        "entity": "food"
      }
    ]
},
```

**Comment by winner484** [comment] 2018-05-03 15:45
@howl-anderson thank you for your great work! may i learn from you , maybe i could help you finish the job?

**Comment by winner484** [comment] 2018-05-03 15:47
@wrathagom thank you

**Comment by buivietan** [comment] 2018-05-04 01:46
@amn41 
I am using Rasa to do Japanese NLU with MITIE and a result is very good. My config_mitie_ja.yml is: 
language: "ja"

pipeline:
- name: "nlp_mitie"
  model: "mitie/total_word_feature_extractor_ja.dat"
- name: "tokenizer_japanese" # I used tinysegmenter as Japanese tokenizer
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn" # I modified the intent classifier. Instead of GridSearchCV I used linear model with Logistic regression as intent classifier. 

My result after training model:
 {'entities': [{'extractor': 'ner_mitie', 'start': 0, 'confidence': None, 'value': '千葉', 'end': 2, 'entity': 'ロケーション'}], 'intent': {'confidence': 0.9422146832263528, 'name': 'レストランを検索する'}, 'intent_ranking': [{'confidence': 0.9422146832263528, 'name': 'レストランを検索する'}, {'confidence': 0.038330105668737326, 'name': '肯定する'}, {'confidence': 0.011094799507902988, 'name': 'さようなら'}, {'confidence': 0.008360411597006933, 'name': '挨拶する'}], 'text': '千葉にレストランを探したい。'}

**Comment by geekboood** [comment] 2018-05-29 01:49
@amn41 I didn't understand how the Supervised Word Vectors work before the corpus feed into tensorflow model yet. Could I just segment a Chinese sentence using some tokenizer such as Jieba, and then join the result with space. Then I put it into the count_vectors_featurizer (maybe I should tweak some parameters here). The result goes straight into the tensorflow_embedding part. Should the above procedure work?

**Closed** 2018-08-09 15:37 UTC
Labels: discussion, help wanted

**Comment by nullphantom** [comment] 2019-09-27 06:29
> @amn41
> I am using Rasa to do Japanese NLU with MITIE and the result is quite good. My config_mitie_ja.yml is:
> language: "ja"
> 
> pipeline:
> 
> * name: "nlp_mitie"
>   model: "mitie/total_word_feature_extractor_ja.dat"
> * name: "tokenizer_japanese" # I used tinysegmenter as Japanese tokenizer
> * name: "ner_mitie"
> * name: "ner_synonyms"
> * name: "intent_featurizer_mitie"
> * name: "intent_classifier_sklearn" # I modified the intent classifier. Instead of GridSearchCV I used linear model with Logistic regression as intent classifier.
> 
> My result after training model:
> {'entities': [{'extractor': 'ner_mitie', 'start': 0, 'confidence': None, 'value': '千葉', 'end': 2, 'entity': 'ロケーション'}], 'intent': {'confidence': 0.9422146832263528, 'name': 'レストランを検索する'}, 'intent_ranking': [{'confidence': 0.9422146832263528, 'name': 'レストランを検索する'}, {'confidence': 0.038330105668737326, 'name': '肯定する'}, {'confidence': 0.011094799507902988, 'name': 'さようなら'}, {'confidence': 0.008360411597006933, 'name': '挨拶する'}], 'text': '千葉にレストランを探したい。'}

Hi. Where you can get `mitie/total_word_feature_extractor_ja.dat` ?

**Comment by aparnak123** [comment] 2019-11-20 21:51
> @wrathagom @winner484 Just for the record, although https://github.com/howl-anderson/Chinese_models_for_SpaCy currently is the only SpaCy model that support Chinese language but it is not the official Chinese language models for SpaCy, and most importantly it is still working in progress. Named Entity Recognition (AKA NER) is currently (2018-05-03) not supported, I am still working on it.

Is there any progress

**Comment by howl-anderson** [comment] 2019-11-21 01:43
@aparnak123 Hi, NER is supported now. See news https://github.com/howl-anderson/Chinese_models_for_SpaCy/blob/master/README.en-US.md#ner-new .
