### ISSUE TITLE
How to get accurate result. 

### ISSUE THREAD

**Issue by baput** [RasaHQ/rasa_nlu#767] opened 2018-01-11 06:20 UTC
**Rasa NLU version** (e.g. `0.7.2`):

**Used backend / pipeline** `mitie`:

**Operating system** linux:

**Issue**:
training data:
```
    {
        "text": "Russia vs Saudi Arabia",
        "intent": "game",
        "entities": [{
            "start": 0,
            "end": 6,
            "value": "Russia",
            "entity": "team1"
          },
          {
            "start": 10,
            "end": 22,
            "value": "Saudi Arabia",
            "entity": "team2"
          },
          {
            "start": 7,
            "end": 9,
            "value": "vs",
            "entity": "vs"
          }

        ]
      },
     {
        "text": "russia vs saudi arabia who will win?",
        "intent": "prediction",
        "entities": [{
            "start": 0,
            "end": 6,
            "value": "Russia",
            "entity": "team1"
          },
          {
            "start": 10,
            "end": 22,
            "value": "Saudi Arabia",
            "entity": "team2"
          },
                   {
            "start": 23,
            "end": 35,
            "value": "who will win",
            "entity": "predict"
          },

        ]
      }

```
Getting output intent as prediction for Russia vs Saudi Arabia but was expecting game.

**Comment by wrathagom** [comment] 2018-01-12 13:25
Is that all of the training data you are providing? I would start with a minimum of 10 examples per intent. Probably 10-20 examples per entity.

In fact with just one example for each intent you likely have an error message or warning in your console that training wasn't successful.

**Comment by baput** [comment] 2018-01-14 07:17
No its just an example for each intent I have around 20 data set

On Friday, January 12, 2018, Caleb M. Keller <notifications@github.com>
wrote:
> Is that all of the training data you are providing? I would start with a
minimum of 10 examples per intent. Probably 10-20 examples per entity.
>
> In fact with just one example for each intent you likely have an error
message or warning in your console that training wasn't successful.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/VdlQjXI3lwZhBKZeyV3F1vDQSPGGwWUonv6ONgO_NOeft1z33HYmv_Yj2a4e3ehRzN5JUgAfaZbF8VdWMSjZT2j4Y0gt_LLvFNsRN_d2L4lRrJBDU_ZsBgYm7_q55F6E1NOsBKaUKy21blWAjKVWx466dg2Yqg=s0-d-e1-ft#https://github.com/notifications/beacon/AH6cg7X3zVqH1zZ9lidkDQPa0o2TjB3Yks5tJ106gaJpZM4RaXwv.gif>

**Comment by wrathagom** [comment] 2018-01-14 15:13
What?

**Comment by baput** [comment] 2018-01-15 05:16
@wrathagom in my training file. I have defined 10-20 data set for every intent.

**Comment by dcolomvakos** [comment] 2018-01-17 19:44
I'm seeing a strange issue with incorrect intents ..even from the vanilla example.  This *used* to work but I wonder if a recent change broke things? 

Training data:

{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "howdy",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey there",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hi",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "i'm looking for a place to eat",
        "intent": "restaurant_search",
        "entities": []
      },
      {
        "text": "i'm looking for a place in the north of town",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 31,
            "end": 36,
            "value": "north",
            "entity": "location"
          }
        ]
      },
      {
        "text": "show me chinese restaurants",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 8,
            "end": 15,
            "value": "chinese",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "yes",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "yep",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "yeah",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "show me a mexican place in the centre",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 31,
            "end": 37,
            "value": "centre",
            "entity": "location"
          },
          {
            "start": 10,
            "end": 17,
            "value": "mexican",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "bye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "goodbye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "good bye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "stop",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "end",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "i am looking for an indian spot",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 20,
            "end": 26,
            "value": "indian",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "search for restaurants",
        "intent": "restaurant_search",
        "entities": []
      },
      {
        "text": "anywhere in the west",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 16,
            "end": 20,
            "value": "west",
            "entity": "location"
          }
        ]
      },
      {
        "text": "central indian restaurant",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 0,
            "end": 7,
            "value": "central",
            "entity": "location"
          },
          {
            "start": 8,
            "end": 14,
            "value": "indian",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "indeed",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "that's right",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "ok",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "great",
        "intent": "affirm",
        "entities": []
      }
    ]
  }
}


[[hey]]

{'entities': [], 'text': 'hey', 'intent_ranking': [{'name': 'affirm', 'confidence': 0.7502150469138059}, {'name': 'greet', 'confidence': 0.1779846805192085}, {'name': 'goodbye', 'confidence': 0.05105513850055021}, {'name': 'restaurant_search', 'confidence': 0.020745134066435023}], 'intent': {'name': 'affirm', 'confidence': 0.7502150469138059}}

I don't see how 'hey' could be labelled as affirm.    Using spacy_sklearn on Anaconda 3.4 windows (same issue on this model deployed on Ubuntu 16)

**Comment by wrathagom** [comment] 2018-01-17 21:31
@dcolomvakos I can't reproduce that using the latest-full docker. for hey I get:

```
{
	"entities": [],
	"intent": {
		"confidence": 0.6514189120999855,
		"name": "greet"
	},
	"text": "hey",
	"intent_ranking": [
		{
			"confidence": 0.6514189120999855,
			"name": "greet"
		},
		{
			"confidence": 0.2283932474024288,
			"name": "affirm"
		},
		{
			"confidence": 0.10576655178519008,
			"name": "goodbye"
		},
		{
			"confidence": 0.014421288712395421,
			"name": "restaurant_search"
		}
	]
}
```

can you post the metadata.json for that specific model. Also out of curiosity what version of spacy are you using?

**Comment by dcolomvakos** [comment] 2018-01-18 13:33
Sure thing, 

$ pip show spacy
Name: spacy
Version: 2.0.5
Summary: Industrial-strength Natural Language Processing (NLP) with Python and Cython
Home-page: https://spacy.io
Author: Explosion AI
Author-email: contact@explosion.ai
License: MIT
Location: c:\anaconda3\lib\site-packages

metadata.json:

{
    "language": "en",
    "intent_classifier_sklearn": "intent_classifier.pkl",
    "training_data": "training_data.json",
    "trained_at": "20180118-083124",
    "entity_synonyms": null,
    "spacy_model_name": "en",
    "rasa_nlu_version": "0.10.6",
    "entity_extractor_crf": {
        "version": 1,
        "model_file": "crf_model.pkl",
        "crf_features": [
            [
                "low",
                "title",
                "upper",
                "pos",
                "pos2"
            ],
            [
                "bias",
                "low",
                "word3",
                "word2",
                "upper",
                "title",
                "digit",
                "pos",
                "pos2",
                "pattern"
            ],
            [
                "low",
                "title",
                "upper",
                "pos",
                "pos2"
            ]
        ],
        "BILOU_flag": true
    },
    "regex_featurizer": null,
    "pipeline": [
        "rasa_nlu.utils.spacy_utils.SpacyNLP",
        "rasa_nlu.tokenizers.spacy_tokenizer.SpacyTokenizer",
        "rasa_nlu.featurizers.spacy_featurizer.SpacyFeaturizer",
        "rasa_nlu.featurizers.regex_featurizer.RegexFeaturizer",
        "rasa_nlu.extractors.crf_entity_extractor.CRFEntityExtractor",
        "rasa_nlu.extractors.entity_synonyms.EntitySynonymMapper",
        "rasa_nlu.classifiers.sklearn_intent_classifier.SklearnIntentClassifier"
    ]
}

**Comment by wrathagom** [comment] 2018-01-18 14:18
@tmbo I wonder if this is a Spacy 2.0 vs spacy 1.0 difference?

@dcolomvakos I remember people saying on another issue that the performance they were getting from spacy 2.0's small model was worse than spacy 1.0 small model. Maybe try installing and linking the medium model?

```
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```

**Comment by dcolomvakos** [comment] 2018-01-18 17:38
@wrathagom 

So I downloaded the spacy web_md and linked it.. now when I run my rasa test code I get this error (which I saw a week ago, something to do with sklearn/scikit array shapes.  This was fixed by updating sklearn..)

```

  File "C:\Anaconda3\lib\site-packages\rasa_nlu\model.py", line 295, in parse
    component.process(message, **self.context)
  File "C:\Anaconda3\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 119, in process
    intent_ids, probabilities = self.predict(X)
  File "C:\Anaconda3\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 154, in predict
    pred_result = self.predict_prob(X)
  File "C:\Anaconda3\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 143, in predict_prob
    return self.clf.predict_proba(X)
  File "C:\Anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 484, in predict_proba
    return self.best_estimator_.predict_proba(X)
  File "C:\Anaconda3\lib\site-packages\sklearn\svm\base.py", line 594, in _predict_proba
    X = self._validate_for_predict(X)
  File "C:\Anaconda3\lib\site-packages\sklearn\svm\base.py", line 459, in _validate_for_predict
    (n_features, self.shape_fit_[1]))
ValueError: X.shape[1] = 300 should be equal to 384, the number of features at training time

```

Also, here is my dependency tree for Rasa and Spacy.  Do you see anything of concern?

Note this is a windows 7 machine,  with Anaconda. I had trouble getting rasa_nlu working on this as it required visual studio c++ libs. 

Anyhow here is the list:
```
$ pipdeptree -p rasa_nlu
Warning!!! Possibly conflicting dependencies found:
* Sphinx==1.3.1
 - sphinx-rtd-theme [required: >=0.1,<0.2, installed: 0.2.4]
* airflow==1.8.0
 - psutil [required: <5.0.0,>=4.2.0, installed: 5.4.3]
 - thrift [required: <0.10,>=0.9.2, installed: 0.10.0]
 - alembic [required: <0.9,>=0.8.3, installed: 0.9.6]
 - flask-login [required: ==0.2.11, installed: 0.4.1]
 - gunicorn [required: >=19.3.0,<19.4.0, installed: 19.7.1]
 - tabulate [required: <0.8.0,>=0.7.5, installed: 0.8.2]
 - future [required: >=0.15.0,<0.16, installed: 0.16.0]
 - flask-wtf [required: ==0.12, installed: 0.14.2]
 - funcsigs [required: ==1.0.0, installed: 1.0.2]
 - jinja2 [required: >=2.7.3,<2.9.0, installed: 2.10]
 - lxml [required: >=3.6.0,<4.0, installed: 4.1.1]
 - flask-admin [required: ==1.4.1, installed: 1.5.0]
 - flask [required: <0.12,>=0.11, installed: 0.12.2]
* python-nvd3==0.14.2
 - python-slugify [required: ==1.1.4, installed: 1.2.4]
------------------------------------------------------------------------
```

```

pipdeptree -p spacy
Warning!!! Possibly conflicting dependencies found:
* Sphinx==1.3.1
 - sphinx-rtd-theme [required: >=0.1,<0.2, installed: 0.2.4]
* python-nvd3==0.14.2
 - python-slugify [required: ==1.1.4, installed: 1.2.4]
* airflow==1.8.0
 - lxml [required: >=3.6.0,<4.0, installed: 4.1.1]
 - future [required: >=0.15.0,<0.16, installed: 0.16.0]
 - tabulate [required: >=0.7.5,<0.8.0, installed: 0.8.2]
 - psutil [required: >=4.2.0,<5.0.0, installed: 5.4.3]
 - flask-wtf [required: ==0.12, installed: 0.14.2]
 - flask-login [required: ==0.2.11, installed: 0.4.1]
 - jinja2 [required: >=2.7.3,<2.9.0, installed: 2.10]
 - alembic [required: >=0.8.3,<0.9, installed: 0.9.6]
 - flask [required: <0.12,>=0.11, installed: 0.12.2]
 - gunicorn [required: >=19.3.0,<19.4.0, installed: 19.7.1]
 - flask-admin [required: ==1.4.1, installed: 1.5.0]
 - thrift [required: >=0.9.2,<0.10, installed: 0.10.0]
 - funcsigs [required: ==1.0.0, installed: 1.0.2]
------------------------------------------------------------------------
spacy==2.0.5
  - cymem [required: <1.32,>=1.30, installed: 1.31.2]
  - dill [required: >=0.2,<0.3, installed: 0.2.7.1]
    - pyreadline [required: >=1.7.1, installed: 2.1]
  - ftfy [required: >=4.4.2,<5.0.0, installed: 4.4.3]
    - html5lib [required: Any, installed: 1.0.1]
      - six [required: >=1.9, installed: 1.11.0]
      - webencodings [required: Any, installed: 0.5.1]
    - wcwidth [required: Any, installed: 0.1.7]
  - msgpack-numpy [required: ==0.4.1, installed: 0.4.1]
    - msgpack-python [required: >=0.3.0, installed: 0.4.8]
    - numpy [required: >=1.9.0, installed: 1.14.0]
  - msgpack-python [required: Any, installed: 0.4.8]
  - murmurhash [required: >=0.28,<0.29, installed: 0.28.0]
  - numpy [required: >=1.7, installed: 1.14.0]
  - pathlib [required: Any, installed: 1.0.1]
  - plac [required: >=0.9.6,<1.0.0, installed: 0.9.6]
  - preshed [required: >=1.0.0,<2.0.0, installed: 1.0.0]
    - cymem [required: >=1.30,<1.32.0, installed: 1.31.2]
  - regex [required: ==2017.4.5, installed: 2017.4.5]
  - requests [required: >=2.13.0,<3.0.0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.11.5]
    - chardet [required: <3.1.0,>=3.0.2, installed: 3.0.4]
    - idna [required: <2.7,>=2.5, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - six [required: Any, installed: 1.11.0]
  - thinc [required: <6.11.0,>=6.10.1, installed: 6.10.1]
    - cymem [required: <1.32,>=1.30, installed: 1.31.2]
    - cytoolz [required: <0.9,>=0.8, installed: 0.8.0]
    - dill [required: Any, installed: 0.2.7.1]
      - pyreadline [required: >=1.7.1, installed: 2.1]
    - msgpack-numpy [required: Any, installed: 0.4.1]
      - msgpack-python [required: >=0.3.0, installed: 0.4.8]
      - numpy [required: >=1.9.0, installed: 1.14.0]
    - msgpack-python [required: Any, installed: 0.4.8]
    - murmurhash [required: >=0.28,<0.29, installed: 0.28.0]
    - numpy [required: >=1.7, installed: 1.14.0]
    - pathlib [required: >=1.0.0,<2.0.0, installed: 1.0.1]
    - plac [required: >=0.9.6,<1.0.0, installed: 0.9.6]
    - preshed [required: >=1.0.0,<2.0.0, installed: 1.0.0]
      - cymem [required: >=1.30,<1.32.0, installed: 1.31.2]
    - six [required: <2.0.0,>=1.10.0, installed: 1.11.0]
    - termcolor [required: Any, installed: 1.1.0]
    - tqdm [required: >=4.10.0,<5.0.0, installed: 4.19.5]
    - wrapt [required: Any, installed: 1.10.11]
  - ujson [required: >=1.35, installed: 1.35]

```
I'm not sure how to downgrade to spacy 1.0. I'll look into it

**Comment by wrathagom** [comment] 2018-01-19 05:09
I'd stay on spacy 2.0 with the md model. Something along those lines will likely become the Rasa default.

@tmbo maybe we should add a note to the installation docs?

**Comment by wrathagom** [comment] 2018-01-19 05:21
@baput can you tell me if your concerns are addressed as well?

**Comment by baput** [comment] 2018-01-23 16:38
```
"text": "will I get central indian restaurant",
"intent": "probability",
"entities": [
{
"start": 0,
"end": 4,
"value": "will",
"entity": "question"
}
{
"start": 11,
"end": 18,
"value": "central",
"entity": "location"
},
{
"start": 19,
"end": 25,
"value": "indian",
"entity": "cuisine"
}
]
},
```
Adding up intents like this to above mentioned example will end in result mismatch with intent like below

`"text": "central indian restaurant",
"intent": "restaurant_search",
"entities": [
{
"start": 0,
"end": 7,
"value": "central",
"entity": "location"
},
{
"start": 8,
"end": 14,
"value": "indian",
"entity": "cuisine"
}
]
},`

**Closed** 2018-03-15 09:42 UTC
Labels: question, waiting for update
