### ISSUE TITLE
Misaligned entity annotation in sentence

### ISSUE THREAD

**Issue by kapilkathuria** [RasaHQ/rasa_nlu#1320] opened 2018-08-16 04:35 UTC
**Rasa NLU version**: 0.13.1

**Operating system** (windows, osx, ...): Windows 7

**Content of model configuration file**:
```yml
language: "en"

pipeline: 
- name: "tokenizer_whitespace"       # Tokenizer. The current tokenizer implementation relies on words being separated by spaces 
- name: "ner_crf"                     # No pre-trained word vectors 
- name: "intent_featurizer_count_vectors"        # Creates bag-of-words representation of intent features. Required for tensorflow_embedding. 
- name: "intent_classifier_tensorflow_embedding"        # Embedding intent classifier
```

**Issue**:

If I have following in my nlu.md file, i.e. no space between 'starting' and '6Nov18', I get following Warning:

WARNING:rasa_nlu.extractors.crf_entity_extractor:Misaligned entity annotation in sentence 'starting6Nov18'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces or punctuation).

**Content of nlu.md**:
```
## intent: find_date
- starting[6Nov18](date_start) 
```

**Comment by Ghostvv** [comment] 2018-08-16 07:55
This is expected behavior, because the sentences are tokenized based on whitespaces. And in your case `starting6Nov18` is one token. If you want to extract it as `6Nov18`, you need to use synonyms:
```
- [starting6Nov18](date_start:6Nov18) 
```

**Comment by akelad** [comment] 2018-08-24 09:29
@kapilkathuria can we close this?

**Closed** 2018-08-24 11:45 UTC
