### ISSUE TITLE
Can add multiple languages in single config?

### ISSUE THREAD

**Issue by Lilylii** [RasaHQ/rasa_nlu#764] opened 2018-01-09 10:28 UTC
**Rasa NLU version** (e.g. 0.7.3):`0.10.5`

**Used backend / pipeline**  (mitie, spacy_sklearn, ...): `nlp_mitie`, `tokenizer_jieba`, `ner_mitie`, `ner_synonyms`, `intent_featurizer_mitie`, `intent_classifier_sklearn`, `ner_duckling`

**Operating system** (windows, osx, ...):`macOS`

**Issue**: 
I want to train multiple languages Chinese(zh) and English(en) in the same config. But some modules in pipeline can't be download for multiple languages, for example, in this config "ner_duckling" is only can be download for "zh", so it can't process the meaning of time in English. how do I download modules in different languages separately? Is there have any solutions on this issue? or can extend the config settings? thanks a lot!

<img width="907" alt="2018-01-09 6 08 43" src="https://user-images.githubusercontent.com/33889325/34715625-32f74b52-f568-11e7-98c5-e2a8b4fe19ad.png">

**Comment by MariamMohamedFawzy** [comment] 2018-01-11 11:31
@Lilylii  I don't have a solution to your issue but I see you are using ner_duckling at the end of the pipeline. Does this work for you? the input to ner_duckling will be the output of the classifier, not the tokens. I have tried this before and it didn't work.

**Comment by wrathagom** [comment] 2018-01-12 14:01
To my knowledge you can't have multiple languages in a single config, but that doesn't prevent you from overriding the default language in the config.

Assuming that you had the MITIE/spacy models installed then you could override the language when you call `/train` with a request something like this: 

```
http://localhost:5000/train?project=my-project-zh&language=zh
```

I haven't tested this, but I know url parameters allow you to override other configurations like pipeline, etc. Let me know if it doesn't seem to be working.

**Comment by tmbo** [comment] 2018-01-15 08:53
There is no out of the box support for multiple languages. But there is no inherent restriction that will prevent you from training / using different models with different languages - atm. there is just no way to specify different configurations for different models.

**Comment by wrathagom** [comment] 2018-01-15 15:33
@tmbo am I right that in theory you could do it all via url parameters (assuming using Rasa as a server)? specify a custom pipeline and/or custom language.

**Comment by tmbo** [comment] 2018-01-15 16:49
Yes, the code itself is fine to handle e.g. multiple different language models of spacy and different pipelines.

**Comment by Lilylii** [comment] 2018-01-18 06:42
@MariamMohamedFawzy  I don't know what you mean.but yes, it work for me. It can extract the input text into time format.

**Comment by Lilylii** [comment] 2018-01-18 08:40
@wrathagom I have tried the way you mentioned, I don't define the project name, so I use ` curl -XPOST localhost:5000/train?project=default -d data/examples/rasa/demo_rasa.json -p ner_duckling -l en` but It shows `no matches found: localhost:5000/train?project=default`
It's not working as well as the Rasa Docs and it really made me very confused. It may be my fault.

@tmbo I want to extract English and Chinese language by curl the same server, and some modules 
 in pipeline only support specific languages, so I just think there is a way to define the specific language for different modules in the config. But yes, just like you said, there is really no good way to solve my problem right now. thanks.

**Comment by wrathagom** [comment] 2018-01-18 13:16
That's not formatted properly. This isn't a command line property, but rather a URL property.

```
curl -XPOST localhost:5000/train?project=default&pipeline=ner_duckling&language=en -d data/examples/rasa/demo_rasa.json
```

**Comment by Lilylii** [comment] 2018-01-19 03:38
@wrathagom It's shows`zsh: parse error near `&'` , I think it wrong in `project=default`
Where are the project settings? thanks for your answering.

**Comment by wrathagom** [comment] 2018-01-19 05:03
I have confirmed that this works:

```
curl --request POST \
  --url 'http://localhost:5000/train?project=null_test&language=en&pipeline=nlp_spacy%2Cner_duckling' \
  --header 'content-type: application/json' \
  --data '{
	"rasa_nlu_data": {
		"common_examples": []
	}
}'
```

@tmbo it looks like there is some code that says if there is only one item in the pipeline then it has to be a pre-configured pipeline. but I'm thinking that ner_duckling by itself should be valid as well right? I can open another issue if you want to address this.

**Comment by tmbo** [comment] 2018-08-09 16:19
This should be fixed with the new configuration format. The server can also load multiple models of different languages. Detecting the language probably won't be part of nlu for now.

**Closed by tmbo** 2018-08-09 16:19 UTC
Labels: question, waiting for update
