### ISSUE TITLE
'NoneType' object has no attribute 'getName'

### ISSUE THREAD

**Issue by slvnperron** [RasaHQ/rasa_nlu#856] opened 2018-02-18 20:20 UTC
**Rasa NLU version** (e.g. `0.7.3`): `0.12.0a1`

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): `spacy_sklearn`

**Operating system** (windows, osx, ...): `Darwin x86_64`

**Issue**: 
I'm running Rasa as an HTTP server. I train a model via the API (succeeds) then call the `/parse` API with any query. RASA takes about 3 minutes to reply back with the following error:
`{ error: '\'NoneType\' object has no attribute \'getName\'' } 'Request failed with status code 500'`

After this error is thrown, the subsequent queries will succeed.

**Content of configuration file** (if used & relevant): Using default config of `docker/full` img

**Stack trace**:

```
2018-02-18 20:11:09+0000 [-] "172.17.0.1" - - [18/Feb/2018:20:11:08 +0000] "POST /parse HTTP/1.1" 500 61 "-" "axios/0.17.1"
Traceback (most recent call last):
  File "/app/rasa_nlu/server.py", line 157, in parse_get
    else threads.deferToThread(self.data_router.parse, data))
  File "/usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "rasa_nlu/data_router.py", line 164, in parse
    response, used_model = self.project_store[project].parse(data['text'], data.get('time', None), model)
  File "rasa_nlu/project.py", line 77, in parse
    response = self._models[model_name].parse(text, time)
  File "rasa_nlu/model.py", line 291, in parse
    component.process(message, **self.context)
  File "rasa_nlu/extractors/duckling_extractor.py", line 128, in process
    matches = self.duckling.parse(message.text, reference_time=ref_time)
  File "/usr/local/lib/python2.7/site-packages/duckling/wrapper.py", line 238, in parse
    return self._parse(input_str, reference_time=reference_time)
  File "/usr/local/lib/python2.7/site-packages/duckling/wrapper.py", line 56, in _parse
    reference_time=reference_time)
  File "/usr/local/lib/python2.7/site-packages/duckling/duckling.py", line 150, in parse
    self.clojure.read(filter_str),
  File "/usr/local/lib/python2.7/site-packages/jpype/_jclass.py", line 65, in _getClassFor
    pyJavaClass = _JavaClass(javaClass)
  File "/usr/local/lib/python2.7/site-packages/jpype/_jclass.py", line 144, in __new__
    bases.append(_getClassFor(bjc))
  File "/usr/local/lib/python2.7/site-packages/jpype/_jclass.py", line 61, in _getClassFor
    name = javaClass.getName()
AttributeError: 'NoneType' object has no attribute 'getName'
ERROR:__main__:'NoneType' object has no attribute 'getName'
```

Related issue: #835

**Comment by wrathagom** [comment] 2018-02-19 02:02
Can you provide some information about your training data? The commands you are using to train, and the command you are using to parse?

**Comment by slvnperron** [comment] 2018-02-19 18:27
Edit: seems like an issue with my pipeline (`"nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn", "ner_duckling"`), which is the default config with docker/full (`config_spacy_duckling.json`). Moving to pre-built `spacy_sklearn` seems to make the problem go away.

@wrathagom I'm using the HTTP API to send the training data and parse.
`http :5001/parse q=Hello project=dev__botpress__all modelId=model_20180219-182404`

**Comment by tmbo** [comment] 2018-02-19 19:07
Using the default pipeline will fix the issue, because it is not using duckling. The above error is within the java connection to duckling, so it doesn't occur if that component is omitted.

**Comment by slvnperron** [comment] 2018-02-19 20:02
@tmbo Thanks. Any idea why a clean container using `rasa/rasa_nlu:latest-full` has issue connecting to duckling? 

Also since the duckling engine is local, we could also decrease the timeout. The current 120s seems a bit off for a local connection.

**Comment by wrathagom** [comment] 2018-02-20 15:17
If I get a chance I'll test the dockerfile full locally here in a bit. You may have better luck running a dockerfile that's 1 or 2 versions older than latest. This was working not that long ago.

Does your machine have plenty of memory? Dockerfile full is a bit of a beast between MITIE + Spacy + JVM.

**Comment by slvnperron** [comment] 2018-02-20 22:30
Thanks Caleb, that's a good point. I allocated 4gb to that container, will
test with older versions and more ram.

**Comment by tmbo** [comment] 2018-02-28 16:18
@slvnperron did that solve your issue?

**Comment by tkalfigo** [comment] 2018-04-03 19:53
We got the same problem.

Rasa NLU version (e.g. 0.7.3): 0.12.0a1
Used backend / pipeline (mitie, spacy_sklearn, ...): spacy_sklearn
Operating system (windows, osx, ...): GNU/Linux x86_64

 No Dockerfile. There is plenty of memory. Duckling version is `1.7.3` and java `openjdk version "1.8.0_151"`.

Any progress?

**Comment by akelad** [comment] 2018-04-05 17:01
@tkalfigo can you post your error message?

**Comment by tkalfigo** [comment] 2018-04-10 20:13
Sorry but for some reason it is no longer reproducible. Will get back to you if it shows up again.

**Comment by tmbo** [comment] 2018-04-10 21:41
I'll close this for now, please let us know if you have any further issues with this.

**Closed by tmbo** 2018-04-10 21:41 UTC
Labels: bug
