### ISSUE TITLE
Timeout behaviour seems inconsistent

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#1579] opened 2018-12-09 18:20 UTC
**Rasa NLU version**: 0.13.7

**Operating system** (windows, osx, ...): Docker/Linux

**Issue**:
Rasa NLU http server sends a timeout after 15 minutes. In the logs you can see this:
`Timing out client: IPv4Address(type='TCP', host='10.28.1.9'`
But this timeout doesn't trigger a timeout on an NGINX proxy though, so the client is left waiting until NGINX times out. The training still goes on after the 15 min though.

So:
- the issue is: timeout not proxied
- question: is there a simple way to override the Klein/Twisted timeout (I did look it up but found nothing that looks easily changeable in Rasa NLU code base?

**Comment by akelad** [comment] 2018-12-12 11:09
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment] 2018-12-13 18:50
@znat I cannot reproduce the timeout behaviour after 15 minutes. Are you running the NLU server as a standalone service? How are you establishing the client connection - through nginx? This is probably related to `twisted`'s `SessionTimeout` parameter, over which we have no control in `Klein`

**Comment by znat** [comment] 2019-01-08 00:48
@ricwo Rasa NLU is a deployment in a K8S cluster with `nginx-ingress`. Indeed, `SessionTimeout`defaults to 15 min. 

Indeed, there is no problem if you just use the standalone NLU server without nginx in between

So does that mean that it's not possible to train more than 15 min with an nginx reverse proxy?


(this ref is just for me)
https://twistedmatrix.com/documents/current/web/howto/web-in-60/session-endings.html

**Comment by ricwo** [comment] 2019-01-09 20:48
@znat are you able to access the ingress-nginx config map? see for instance https://stackoverflow.com/questions/52008835/nginx-ingress-timeouts-connection-drops?rq=1

**Comment by znat** [comment] 2019-01-10 22:46
@ricwo yes, the timeout in the config-map is set to 1800 secs. But Twisted times out after 900s. And Twisted timeout is not forwarded by nginx. 
I'm not sure what the issue is: locally, twisted timing out does not prevent the web service to respond 200 when training takes more than 15 min, but behind nginx-ingress, after twisted times out the webservice response is ignored by nginx which keeps the request open until the timeout defined in the config-map is triggered

**Comment by akelad** [comment] 2019-03-27 17:33
since we've moved to a different server i'm gonna close this. let me know if you're still experiencing issues

**Closed by akelad** 2019-03-27 17:33 UTC
