### ISSUE TITLE
specifying fixed_model_name in config.json doesn't work

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#668] opened 2017-10-30 18:15 UTC
**Rasa NLU version** : 0.10.x

**Issue**:
A standard `model_[day_time]` folder is created

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "ner_duckling", "intent_classifier_sklearn"],
  "data" : "./output/training.json",
  "language": "en",
  "fixed_model_name" :"model_current",
  "path": "./projects",
  "project":"default",
  "duckling_dimensions":["time", "number", "amount-of-money"]
}
```

The following works though
```
trainer.persist('./projects/', fixed_model_name="current")
```

**Secondary issue**: `current`will not be picked as an available model because it doesn't follow the `model_[day_time]` pattern

**Comment by wrathagom** [comment] 2017-11-02 03:00
Closing duplicate of #634

**Closed by wrathagom** 2017-11-02 03:00 UTC
