### ISSUE TITLE
emoji entity training misalignment

### ISSUE THREAD

**Issue by mnannt** [RasaHQ/rasa_nlu#534] opened 2017-08-17 08:50 UTC
**rasa NLU version** (e.g. `0.7.3`): `0.10.0a1`

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): `spacy_sklearn`

**Operating system** (windows, osx, ...): `mac os`

**Issue**:
I have a expressions file with emojis tagged as entities:
```
{
        "text": "i want 👞",
        "intent": "get_products",
        "entities": [
          {
            "start": 7,
            "end": 8,
            "entity": "category",
            "value": "shoes"
          }
        ]
      },
```
I now used length 1 for the emoji. When I train this via the /train api-endpoint everything is fine and also entity-extraction via the parse-endpoint works well. When I train it via the `rasa_nlu.train` python-command, i get the message:
```
WARNING:rasa_nlu.extractors.crf_entity_extractor:Misaligned entity annotation in sentence 'i want 👞'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces).
```
Also my atom-editor tells me, that one emoji has the length 2. But if I change it to a length of two (start: 7, end: 9), the training via python api works well, but then the training via the api-endpoint gives the same misalignment-warning as the python endpoint before.

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment] 2017-08-17 09:20
That is an interesting behaviour. I will test it in a minute. Which version did you use? (you put unreleased master (0.9.1) there which is somewhat unclear, because the unreleased master would be `0.10.0a1` and `0.9.1` would be the currently released pypi version)

**Comment by mnannt** [comment] 2017-08-17 09:27
Sorry. I pulled from master yesterday. I just looked into the CHANGELOG.rst and have seen that last released version according to this was 0.9.0, so I thought 0.9.1 would be next.
Where do I get the current version number when pulled from master, or should I just name the last commit? ( 28177271504766d5e54eb49605897a470fbe0598 )

**Comment by tmbo** [comment] 2017-08-17 09:31
Alright :+1: 
```
import rasa_nlu
print(rasa_nlu.__version__)
```
will give you the current version (or have a look into the `rasa_nlu/version.py`) file.

It might just be that the encoding of your stored file is not utf-8, not sure if that can be handled properly.

**Comment by tmbo** [comment] 2017-08-18 08:37
Okay, I had a look at this and it is quite an interesting problem.

Some of the emojis have a two character representation (because they are positioned in higher levels of the unicode set and dont fit in the common 16bit character representations). 

Therefore, for some emojis this happens:
```
>>> len(u'🍕')
2
```
which leads to the unaligned tokens. What makes this even harder to fix is, that different versions of python handle this differently and how they handle it depends if the python interpreter is compiled with the `wide` flag being set or not.

Gist: I don't see an easy way to fix this at the moment. There is a library called `uniseg-python` which can split a stream of unicode characters into so called graphemes (a grapheme is basically a "visible character" and can consist of multiple characters as the 🍕) . 

You can use the markdown data format though, which should work because the offsets are calculated in python.

**Comment by tmbo** [comment] 2017-08-18 08:42
I couldn't reproduce the difference in behaviour between training using the server or the script. For the same setup (same version of python on the same machine) I got consistent results (so either training failed for both of them or it succeeded)

**Comment by mnannt** [comment] 2017-08-18 08:52
Thanks Tom, i will check if maybe on my side something is wrong with the file-encoding or the way I do the post-request that leads to the different result and will also check out the markdown-format. And if I just stick to one training method it will lead to consistent results.

**Comment by tmbo** [comment] 2017-09-01 10:05
let me know if you got new insights :+1: I will close this for now as this is more of a python issue and as long as the symbol is consistently treated as one or two characters that should be fine.

**Closed by tmbo** 2017-09-01 10:05 UTC
Labels: bug
