### ISSUE TITLE
Training Rasa NLU docker image on Amazon Linux fails with BrokenProcessPool error

### ISSUE THREAD

**Issue by shashijeevan** [RasaHQ/rasa_nlu#1231] opened 2018-07-12 10:18 UTC
**Rasa NLU version**: Latest

**Operating system** (windows, osx, ...): Amazon Linux on AWS

**Content of model configuration file**: Attached

**Issue**:
I am able to run and train the Rasa NLU on Ubuntu successfully. But, when I try to do the same on Amazon Linux the training step generates an error.

Could any of the dev team help me resolve this issue?

Following are the details

Step1: Running the Docker image with volume mapping
>>docker run -d -p 5000:5000 -v `pwd`/data:/app/data -v `pwd`/logs:/app/logs -v `pwd`/proj:/app/projects rasa/rasa_nlu:latest-full

Step 2: Training with demo data
>>cat demo-rasa.json | curl --request POST --header 'content-type: application/json' -d@- --url 'localhost:5000/train?project=test_model'

This is failing with an error. Container logs shows the following message.

>>docker logs 7b831341f489

2018-07-12 09:02:12+0000 [-] Log opened.
2018-07-12 09:02:12+0000 [-] Site starting on 5000
2018-07-12 09:02:12+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f4990e12438>
2018-07-12 09:02:16+0000 [-] "172.17.0.1" - - [12/Jul/2018:09:02:15 +0000] "GET /status HTTP/1.1" 200 294 "-" "curl/7.53.1"
2018-07-12 09:02:26+0000 [-] 2018-07-12 09:02:26 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'concurrent.futures.process.BrokenProcessPool'>: A process in the process pool was terminated abruptly while the future was running or pending.
2018-07-12 09:02:26+0000 [-] ]
2018-07-12 09:02:26+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 500, in errback
            self._startRunCallbacks(fail)
          File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/app/rasa_nlu/server.py", line 351, in train
            RasaNLUModelConfig(model_config), model_name)
          File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/app/rasa_nlu/data_router.py", line 325, in training_errback
            failure.value.failed_target_project)
        builtins.AttributeError: 'BrokenProcessPool' object has no attribute 'failed_target_project'

2018-07-12 09:02:26+0000 [-] "172.17.0.1" - - [12/Jul/2018:09:02:24 +0000] "POST /train?project=test_model HTTP/1.1" 500 5711 "-" "curl/7.53.1"
[demo-rasa.zip](https://github.com/RasaHQ/rasa_nlu/files/2188159/demo-rasa.zip)

**Comment by pinterb** [comment] 2018-07-13 20:50
I just encountered a similar issue.  I could build a container locally and and also run locally in that container where both the host OS and container are Ubuntu.  I then deployed to Google GKE which is running Container-Optimized OS and I basically get the same error as @shashijeevan

**Comment by akelad** [comment] 2018-08-02 08:03
Have any of you managed to resolve this yet? Seems there's an issue with the process pool but it's not immediately clear as to what it could be

**Comment by znat** [comment] 2018-10-20 23:57
Also encountered the problem on GKE. Thanks to this issue I understood it was an orcherstration related issue, which hinted a possible storage volume problem. `projects` in `--paths projects` wasn't mounted on any volume. That fixed the issue.

Then it uncovered a new one as my training set started growing:`builtins.AttributeError: 'CancelledError' object has no attribute 'failed_target_project'` which turned out to be the proxy timing out after 60 seconds.

Those missing 'failed_target_project' left the project in `training` status, forcing to kill the pod to restore the service. That is the real Rasa issue I think.

**Comment by akelad** [comment] 2018-10-23 11:36
@amn41 any ideas?

**Comment by CarolWu1206** [comment] 2018-10-24 07:52
met the same error with 0.13.7. Is there any workaround?

**Comment by znat** [comment] 2018-10-24 23:22
@carolWu1206 Are you sure your volumes are mapped to actual drives?

**Comment by CarolWu1206** [comment] 2018-10-25 01:54
@znat Yes. I'm running RASA in K8S, and reduced the pod cpu and memory limitation, then I can reproduce the error every time. So I guess it is related to resource.
The problem is, after meeting this error, the training will be marked ongoing forever, so I cannot trigger the training again untill the pod is restarted. But in fact, it is already failed and stopped.

**Comment by znat** [comment] 2018-10-25 02:18
What is the last container log entry?

**Comment by gauravbrills** [comment] 2018-10-25 18:44
> Also encountered the problem on GKE. Thanks to this thread I understood it was orchestration related, which hinted a possible storage volume problem. `projects` in `--paths projects` wasn't mounted on any volume. That fixed the issue.
> 
> Then it uncovered a new one as my training set started growing:`builtins.AttributeError: 'CancelledError' object has no attribute 'failed_target_project'` which turned out to be the proxy timing out after 60 seconds.
> 
> Those missing `failed_target_project` left the project in `training` status, forcing to kill the pod to restore the service. That is the real Rasa issue I think.

I guess we should have an asynch training endpoint [tracked by some training id] instead of it being synchronous . This will help in training specially through HTTP ednpoints

**Comment by znat** [comment] 2018-10-30 00:49
I had `BrokenProcessPool` errors again, not storage related anymore (see above). The model has 275 intents and has a higher cpu/memory footprint. So I suppose this errors also occur when training takes more than the remaining resources available on a cluster.

**Comment by CarolWu1206** [comment] 2018-10-30 01:45
I'm using the built-in TensorFlow pipeline for categorization, and found that the memory usage is increased each time I train. There is memory leak somewhere.

**Comment by akelad** [comment] 2018-10-30 12:56
Thanks for providing all these details guys, we'll make sure to take a look what's going wrong there

**Comment by akelad** [comment] 2018-12-12 11:09
@ricwo you worked on fixing this -- any ideas?

**Comment by marrouchi** [comment] 2019-02-22 17:49
This issue is due to a client request timeout (ESOCKETTIMEDOUT Error). The problem appears when for example the training process takes a long time. I guess, Rasa server must deal with the case when the client drops the connection before any response has been sent out.

**Comment by ricwo** [comment] 2019-03-27 17:42
@marrouchi @znat @shashijeevan are you still experiencing this issue?

**Comment by marrouchi** [comment] 2019-04-08 21:55
@ricwo , Yes i faced the issue again when having a large dataset. After further investigation i found that the issue is also related to memory since i cannot reproduce the issue locally while the server has only ~700Mb available. I've added a 1Gb SWAP, and i did not encounter the error message again.

**Comment by ricwo** [comment] 2019-04-09 09:02
Closing this as more memory resolves the issue

**Closed by ricwo** 2019-04-09 09:02 UTC
Labels: bug
