### ISSUE TITLE
How to judge the classified intent is correct?

### ISSUE THREAD

**Issue by lllkjh** [RasaHQ/rasa_nlu#583] opened 2017-09-12 03:35 UTC
**rasa NLU version** (e.g. `0.7.3`): 0.10.0a1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): mitie + sklearn

**Operating system** (windows, osx, ...): osx

**Issue**: Since rasa will anyhow classify the sentence into a trained intent with confidence score, I just want to check with you talents how you deal with these confidence scores to decide whether a sentence truly belongs to a intent in actual applications? (i.e. leave it unknown if not clearly classified) At my point of view, a constant threshold may not be a good approach. 

Appreciate to share with us your methods for this issue. Thanks. 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment] 2017-09-13 09:33
This is indeed not an easy problem. The confidence score hints the confidence of the model, but it might not be calibrated very well (e.g. a score of `0.80` doesn't necessarily mean that the model is statistically wrong in one of five examples of this kind. it rather means something like: "I am more confident for the last example where I told you the score is `0.70`). 

The broader scope of this is "out of scope detection". Therefore, I will close this as a duplicate of #387.

**Closed by tmbo** 2017-09-13 09:33 UTC
Labels: question
