### ISSUE TITLE
Tensorflow embedding sensitivity Part2

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1317] opened 2018-08-15 15:04 UTC
Hey,

I thought words which are not trained have no weight on classification?

But I found, that like:

`amount money`

is corectly classified (word `amount` is not part of training data! Money is though)

But 

`money`

gets a different Intent!

Although it should be same since `amount` was not learned.

My config:

```

language: "de"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"

```

**Comment by Ghostvv** [comment] 2018-08-15 16:04
interesting observation, would it be possible for you to share the training data, so I could reproduce it locally. I tried it on my dataset and I get precisely the same results for similar case

**Comment by ctrado18** [comment] 2018-08-15 16:10
> interesting observation

I feel I do many interesting observations everytime. :smile: ;)

Normally this should not the case since the word has no weight?
So, if there would be somehow some imbalance this should even not matter?

How would I give you the data privately?

**Comment by Ghostvv** [comment] 2018-08-15 16:25
you can send the data to hi@rasa.com

**Comment by ctrado18** [comment] 2018-08-15 16:38
what is this address? Have you created it for me?

What about my other questions above?;)

**Comment by Ghostvv** [comment] 2018-08-15 16:47
this is the contact email address for general inquires, you can send the data privately there.

Regarding you other questions:
As I said, I check it locally with our datasets, and the algorithm gives precisely the same results with and without additional unseen words. So they indeed have no weights. I think there is some other issue in your case.
please check forum.rasa.com there is a thread for ideas, etc

**Comment by ctrado18** [comment] 2018-08-15 16:52
> So they indeed have no weights.

So, there might be a bug, otherwise the intent shouldn't change even if I would have imbalances?

**Comment by Ghostvv** [comment] 2018-08-15 17:07
Not that I aware of. Unfortunately, I cannot debug it, until you provide the script to reproduce it.

**Comment by ctrado18** [comment] 2018-08-15 17:18
No I found an imbalance and removed it such that I have roughly 30 examples for 4 intents now. No this issues is removed?! So it seems there is a bug. Maybe this should investigated more carefully. Do whitespaces palay a role for intents? Maybe it was so overfitting in my case that this one whitespace did the thing...

**Comment by Ghostvv** [comment] 2018-08-15 18:02
If you send us the scripts to reproduce the issue, we can investigate it further.

**Comment by ctrado18** [comment] 2018-08-15 18:15
what about this "token_pattern": r'(?u)\b\w\w+\b',?

**Comment by Ghostvv** [comment] 2018-08-16 07:39
Please see `sklearn`'s documentation for this: http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

token_pattern : string
Regular expression denoting what constitutes a “token”, only used if analyzer == 'word'. The default regexp select tokens of 2 or more alphanumeric characters (punctuation is completely ignored and always treated as a token separator).

**Comment by Ghostvv** [comment] 2018-08-16 07:40
Since you diagnosed the problem: https://github.com/RasaHQ/rasa_nlu/issues/1319. I'll close this issue.

**Closed by Ghostvv** 2018-08-16 07:40 UTC

**Comment by ctrado18** [comment] 2018-08-16 08:03
Yeahh but you overwrote token_pattern...with this regex...What is the meaning of this regex?

Did I find the solution in #1319?

**Comment by Ghostvv** [comment] 2018-08-16 08:09
this regex is default sklearn's regex for `token_pattern` which picks the words of 2 or more characters and ignores punctuation and whitespaces. For regex documentation please refer to: https://docs.python.org/3.6/library/re.html
